site_name: Lodestone Docs
repo_name: Lodestone
repo_url: https://github.com/Lodestone-Team/lodestone
site_description: Documentation for the Lodestone Project
theme:
    name: dracula
plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
nav:
  - ğŸ  Home: index.md #This is the first page you land on when you visit "Home"
  - ğŸš€ Getting Started for Developers: Getting Started for Developers.md
  - ğŸ“œ README.md: Project README.md
  - ğŸ—‚ï¸ Project Overview: Project Overview.md 
  - ğŸ‘· Release Pipeline: #This is a tab on my page as I'm using the tabs feature for navigation.
    - Release/Integration Process.md 
    - Release/Build Process.md 
    - Release/Deployment Process.md 
    - Release/Monitoring Process.md 
  - ğŸ“š Documentation: Read The Docs.md
 